### ISSUE TITLE
what to export and what not to export

### ISSUE THREAD

**Issue by statsccpr** [carloscinelli/sensemakr#17]
now in cleaning / orgnizing mode

i'm thinking a lot of the low level functions should NOT be exported, while some of the higher level functions should be.

# Things NOT to export

getstats
benchmarkr
groupR2
get_bias
get_se
get_t
adjust_estimate
t_to_r2

# Things to Export

S3method(plot,sensemakr)
S3method(print,sensemakr)
S3method(print,summary.sensemakr)
S3method(sensemakr,lm)
S3method(summary,sensemakr)
export(class_df_from_term)
export(contourplot)
export(interpret)
export(sensemakr)
export(worstcaseinterpret)
export(worstcaseplot)

are users really going to use these directly? I don't think so. Evenmore so, users will not use these functions OUTSIDE of the sensemakr package thru

```
sensemakr:::benchmarkr(some_non_sensemakr_application)
```

On the other hand, as argued in https://github.com/chadhazlett/sensemakr/issues/14
some of the plotting functions might be directly accessed by users

https://cran.r-project.org/web/packages/roxygen2/vignettes/namespace.html

**Comment by chadhazlett** [comment]
I agree it will be very rare for users to access those directly so let's
not export

On Sep 12, 2017 10:42 AM, "statsccpr" <notifications@github.com> wrote:

now in cleaning / orgnizing mode

i'm thinking a lot of the low level functions should NOT be exported, while
some of the higher level functions should be.

Not to export

   - getstats
   - benchmarkr
   - groupR2
   - get_bias
   - get_se
   - get_t
   - adjust_estimate
   - t_to_r2
   - class_df_from_term

are users really going to use these directly? I don't think so

On the other hand, as argued in as in #14
<https://github.com/chadhazlett/sensemakr/issues/14>
some of the plotting functions might be directly accessed by users

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/chadhazlett/sensemakr/issues/17>, or mute the thread

**Comment by statsccpr** [comment]
reduced list of exported functions in this commit
https://github.com/chadhazlett/sensemakr/commit/5f81481133e51aed7336c828c119bd745e5a80df

these helper functions now share a single documentation page: ?get_bias
https://github.com/chadhazlett/sensemakr/commit/709dbe2fc779de400f1cc53524f231c62afa7c77

**Comment by statsccpr** [comment]
closing for now, seems like list in initial post is a good final set of not to export vs export,
can revisit if feel otherwise
