### ISSUE TITLE
QUESTION: there is a mismatch between summary output

### ISSUE THREAD

**Issue by statsccpr** [carloscinelli/sensemakr#21]
question posed in vignette

https://github.com/chadhazlett/sensemakr/blob/master/vignettes/sensemakr.md#benchmarking-summary

```
QUESTION: there is a mismatch between these two. Is this what we want?

MT: here?
## ---Using the covariate most strongly associated with the treatment assignment as a benchmark---
## ---Using the covariate most strongly associated with the outcome as a benchmark---

```
not clear what the mismatch is

**Comment by chadhazlett** [comment]
I have addressed this already, apologies. Please close. Thanks

On Sep 13, 2017 4:02 PM, "statsccpr" <notifications@github.com> wrote:

question posed in vignette

https://github.com/chadhazlett/sensemakr/blob/master/vignettes/sensemakr.md#
benchmarking-summary

QUESTION: there is a mismatch between these two. Is this what we want?

MT: here?
## ---Using the covariate most strongly associated with the treatment
assignment as a benchmark---
## ---Using the covariate most strongly associated with the outcome as
a benchmark---


not clear what the mismatch is

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/chadhazlett/sensemakr/issues/21>, or mute the thread
