### ISSUE TITLE
Problem with help manual?

### ISSUE THREAD

**Issue by chadhazlett** [carloscinelli/sensemakr#25]
After some time using sensemakr, the following appears in the console:

Error in fetch(key) : 
  lazy-load database '/home/chad/R/x86_64-pc-linux-gnu-library/3.3/sensemakr/help/sensemakr.rdb' is corrupt

Also, possibly related, if the vignette is loaded, then attempting to access the help file thereafter does not seem to work.

**Comment by statsccpr** [comment]
I'm 99% sure this is an R / install_github() issue

https://github.com/hadley/devtools/pull/1001

seems like restarting the r session is the fix for all these database error situations whenever someone
loads an old version of package, github install a new version, looks up documentation.
seems like the old and new versions get mixed up.

Can you restart your r session and try to recreate the problem?
or even one step further, uninstall sensemakr, install the new version, restart the r session, then recreate the problem?

With that workflow, I do not encounter the error in mac or linux environments

![screen shot 2017-09-17 at 11 46 30 am](https://user-images.githubusercontent.com/17146552/30524800-3379d7f6-9baf-11e7-9f39-453d7adab714.png)


```
# devtools::install_github("chadhazlett/sensemakr",build_vignettes = TRUE,force=TRUE)
# restart R session

library(sensemakr)


# iterate between vignette() 
# and ? help doc

?sensemakr
vignette('sensemakr','sensemakr')

?sensemakr.lm
vignette('sensemakr','sensemakr')

?print.sensemakr
vignette('sensemakr','sensemakr')

?summary.sensemakr
vignette('sensemakr','sensemakr')

?print.summary.sensemakr
vignette('sensemakr','sensemakr')

?plot.sensemakr
vignette('sensemakr','sensemakr')

?contourplot
vignette('sensemakr','sensemakr')

?worstcaseplot
vignette('sensemakr','sensemakr')

?get_bias
?get_se
?get_t
?adjust_estimate
?t_to_r2
?group_r2

vignette('sensemakr','sensemakr')

```

**Comment by chadhazlett** [comment]
Restarting does remove it for a while but I'm not sure what makes it come
back.  At any rate as long as its a github_install issue that's manageable.

**Comment by statsccpr** [comment]
closing, but if it pops up again, further investigation is needed
