### ISSUE TITLE
Label placement on plots

### ISSUE THREAD

**Issue by chadhazlett** [carloscinelli/sensemakr#26]
We knew this would be an issue, and if we can't solve it right now, okay. But the overlap in the label positions is problematic indeed.

**Comment by statsccpr** [comment]
im thinking an immediate thing to do is keep the current label positions, add an optional null argument to turn it off.

then leave it to the user to label the points themselves along the lines of


https://gist.github.com/slowkow/003b4d9f3f59cee8551c

instead of directly incorporating these extra package dependencies leave it to the user to go the extra step. the wordcloud example seems like an ez extra end-user side customization.

mike

On Sep 16, 2017 6:02 PM, Chad Hazlett <notifications@github.com> wrote:

We knew this would be an issue, and if we can't solve it right now, okay. But the overlap in the label positions is problematic indeed.

**Comment by statsccpr** [comment]
i quickly threw together 3 different methods for post-processing label placements the end-user can pursue

* manually via locator()
* algorithmically via 'maptools' package
* algorithmically via 'FField' package

https://github.com/chadhazlett/sensemakr/blob/master/tools/label_coord_custom_ex.R

I think they should not be formally integrated into sensemakr, to keep the package dependencies lightweight. That is, keep these as commented out examples in the documentation of plot, or add a section into the vignette

the maptools method via genetic algorithm and simulated annealing does pretty good

**Comment by statsccpr** [comment]
Added 'End-User Label Placements' section to vignette

https://github.com/chadhazlett/sensemakr/blob/master/vignettes/sensemakr.md#end-user-label-placements

**Comment by chadhazlett** [comment]
Thanks Michael.
My sense is we should go with this approach for now and to get this thing
moving.
In the next version we can consider bringing this inside the package, with
a "suggests" dependency.
