### ISSUE TITLE
last step to choose style <- vs = etc

### ISSUE THREAD

**Issue by statsccpr** [carloscinelli/sensemakr#7]
lets save it to the end where we enforce our code style

eg using <- instead of =

**Comment by statsccpr** [comment]
Related to internal style

https://github.com/chadhazlett/sensemakr/issues/12

**Comment by chadhazlett** [comment]
I'd like to use "=" rather than "<-".

I know HW recommends "<-".  My argument for "=" is that

(a) I've rarely had errors related to using "=", but numerous times I've
had errors related to "<-" when I wanted to test if 'a' was less than
'negative b'.

(b) because it's not a closed case as to which is better, and there is no
need to be religious about this, I'd rather represent the (minority) view
that it's okay to use the thing used in almost every other language, "=".

Of course there are many other style issues to settle.

**Comment by statsccpr** [comment]
done in 

https://github.com/chadhazlett/sensemakr/commit/0741cfd7682f7a60174e326cbf6e6893d4516861
